### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by MegaV0lt** [kfb77/vdr-plugin-markad#1]
https://github.com/kfb77/vdr-plugin-markad/blob/ffea96644fb9d23770ec6d9d280f6aa585c5d528/HISTORY#L11
"Ubunti" -> "Ubuntu" ; Right?

**Comment by kfb77** [comment]
thanks, fixed in [4c4ff34](https://github.com/kfb77/vdr-plugin-markad/commit/4c4ff345dc2e4c1fbb32e7d335a98cfed96b3829)
