### ISSUE TITLE
spelling errors

### ISSUE THREAD

**Issue by christmart** [kfb77/vdr-plugin-markad#13]
When building vdr-plugin-markad for Debian lintian flagged some spelling errors in the source.
Find attached the patch which fixes the errors.
[spelling-patch.txt](https://github.com/kfb77/vdr-plugin-markad/files/13989351/spelling-patch.txt)

**Comment by kfb77** [comment]
WOW, a lot of spelling errors, thank you very much.
Your patch was applied to branch V03 and will be part of the next release.
How have you done this ? I want to integrate the check in my build scripts.

**Comment by christmart** [comment]
I use the Debian tool lintian for my build pipeline. lintian checks for a lot of different problems in the Debian packages. I am not sure which tools is called for spellchecking. But you can call /usr/share/lintian/bin/spellintian from the package to check files for spelling errors:
```
/usr/share/lintian/bin/spellintian HISTORY
HISTORY: unsuported -> unsupported
HISTORY: menue -> menu
HISTORY: reencode -> re-encode
HISTORY: informations -> information
```
btw. I did not correct reencode to re-encode in the patch, because I think that both versions are ok.
But, if you want to make lintian happy, you might change this too.

**Comment by kfb77** [comment]
Thx, the tool still find more spelling errors.
I will these fix too.
