### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by MegaV0lt** [kfb77/vdr-plugin-markad#2]
https://github.com/kfb77/vdr-plugin-markad/blob/ffea96644fb9d23770ec6d9d280f6aa585c5d528/HISTORY#L11

Same Typo as in V2 Branch ;-)

**Comment by kfb77** [comment]
thanks again, same code base, same typo.
Fixed in [68cd574](https://github.com/kfb77/vdr-plugin-markad/commit/68cd5749c42f8ed3fa691b9e2745945ea894785f), master and V02 will done by future merge
