### ISSUE TITLE
Erkennung auf arte hd oder 3sat hd

### ISSUE THREAD

**Issue by MegaV0lt** [kfb77/vdr-plugin-markad#7]
Die Marken stimmen in letzter Zeit nicht mehr. 
 Hier mal ein Log:
https://www.dropbox.com/s/ntrqszb514tftsg/markad.log

Es wird anscheinend kein Logo erkannt
Sender arte HD auf Astra 19,2°Ost

**Comment by kfb77** [comment]
Du nutzt ein eigenes Logo aus /var/lib/markad, das vermutlich veraltet ist:
cMarkAdLogo::Load(): file found for logo arte_HD-A16_9 plane 0 in /var/lib/markad

Gib markad eine Change, selbst ein besseres zu finden und lösche das veraltete Logo, oder besser gleich alle.

**Comment by MegaV0lt** [comment]
Komisch. Ich dachte ich hätte die schon mal gelöscht. 

darkwing@vdr01:~$ ll /var/lib/markad
insgesamt 2,9M
drwxr-xr-x  2 vdr  vdr   24K Mai 30 14:14 ./
drwxr-xr-x 61 root root 4,0K Feb 10 10:52 ../
-rwxr-xr-x  1 vdr  vdr   19K Feb  2 16:12 3sat-A16_9-P0.pgm*
-rwxr-xr-x  1 vdr  vdr   15K Feb  2 16:12 3sat_HD-A16_9-P0.pgm*
...
darkwing@vdr01:~$ sudo rm -f /var/lib/markad/*
[sudo] Passwort für darkwing: 
darkwing@vdr01:~$ ll /var/lib/markad
insgesamt 32K
drwxr-xr-x  2 vdr  vdr   24K Jul 15 07:02 ./
drwxr-xr-x 61 root root 4,0K Feb 10 10:52 ../

Kam vielleicht mit einem Update...
