### ISSUE TITLE
bug: address is checked, but probably never m

### ISSUE THREAD

**Issue by wirbel-at-vdr-portal** [kfb77/vdr-plugin-markad#8]
Hi kfb77,

i'm stumbling about this compiler message. Strange..

-----------------------------------------------------
 logo.cpp: In member function 'bool cExtractLogo::CheckValid(const sMarkAdContext*, const sLogoInfo*, int, int, int)':
 logo.cpp:820:27: warning: the address of 'sLogoInfo::valid' will never be NULL [-Waddress]
   820 |     if (!ptr_actLogoInfo->valid) {
       |          ~~~~~~~~~~~~~~~~~^~~~~
 In file included from logo.cpp:11:
 logo.h:37:10: note: 'sLogoInfo::valid' declared here
    37 |     bool valid[PLANES] = {}; //!< <b>true:</b> data planes contain valid data <br>

-----------------------------------------------------
It looks like, that logo.cpp:820 (and logo.cpp:916) tries to check, if the struct sLogoInfo's member 'valid' was ever assigned and is now safe to use.

However, it is defined as a _static array_ of bools.

It's initialized to {}, which translates to {0,0,0} which also not nice, as it assumes false to be implemented as zero. Should be {false, false, false}, may be worth to create a class with constructor instead.

Looks like a bug. Either remove that check in line 820 and 916, as this member cannot be empty address.
Or, provide an index and check for one or more of its bool members.

**Comment by wirbel-at-vdr-portal** [comment]
Second issue, same file. logo.cpp, around 1440

actLogoInfo.sobel = new uchar*[PLANES];
(..)
delete actLogoInfo.sobel;


The last line is _wrong_, as it calls the _wrong version_ of the delete operator, and may cause a memory leak. See also https://stackoverflow.com/questions/2425728/delete-vs-delete-operators-in-c; example #3 in second answer.

That line needs to be changed into
delete[] actLogoInfo.sobel;

In general if we have an array and have used new, we should use delete[] instead od delete.

**Comment by kfb77** [comment]
Thanks for your contribution.
I fixed it in branch [issue#8](https://github.com/kfb77/vdr-plugin-markad/tree/issue%238). Please check my patch.

> "However, it is defined as a static array of bools."

And here is the bug, I changed the code to a single value and forget to change the declaration.

> That line needs to be changed into delete[] actLogoInfo.sobel;

done as you suggested

**Comment by kfb77** [comment]
I found a new bug, the logo function is now broken. Wait for my fix before your test.

**Comment by kfb77** [comment]
After a deeper look in the code, I found out, "valid" is never set. It only works because of the bug, checking the pointer to a static array which is always true. I removed variable "valid" completely. Now please test.

**Comment by wirbel-at-vdr-portal** [comment]
Looks fine. :)

**Comment by kfb77** [comment]
Merged to V03, close issue.
